### PR TITLE
Add the changes that involves Different Methods, Overloading.

### PR DESCRIPTION
**Pull request by RaduDontov**
This branch contains details about static and instance methods. Random.Generations and Customer class detailss.

### CODE REVIEW

**Review by mihai1996 — DISMISSED** [review]
In the class Customer, the body of the "else" instruction is empty (line 16). Delete it or add something.

**Review by Mia077 — APPROVED** [review]

**Comment by RaduDontov** [comment]
Hello

**Comment by RaduDontov** [comment]
hello

**Comment by RaduDontov** [comment]
hello

**Comment by RaduDontov** [comment]
hello

**Comment by RaduDontov** [comment]
Add the changes that involves Different Methods, Overloading.

**Comment by RaduDontov** [comment]
Add the changes that involves Different Methods, Overloading.

**Pull request merged**
